create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null constraint profiles_display_name_check check (length(trim(display_name)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null constraint companies_name_check check (length(trim(name)) > 0),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.facilities (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id),
  name text not null constraint facilities_name_check check (length(trim(name)) > 0),
  prefecture text not null constraint facilities_prefecture_check check (length(trim(prefecture)) > 0),
  city text not null constraint facilities_city_check check (length(trim(city)) > 0),
  address_line text not null constraint facilities_address_line_check check (length(trim(address_line)) > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.meeting_rooms (
  id bigint generated by default as identity primary key,
  facility_id bigint not null references public.facilities(id),
  name text not null constraint meeting_rooms_name_check check (length(trim(name)) > 0),
  capacity integer not null constraint meeting_rooms_capacity_check check (capacity >= 1),
  hourly_rate integer not null constraint meeting_rooms_hourly_rate_check check (hourly_rate >= 0),
  description text,
  image_path text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipments (
  id bigint generated by default as identity primary key,
  name text not null constraint equipments_name_check check (length(trim(name)) > 0),
  unit_price integer not null constraint equipments_unit_price_check check (unit_price >= 0),
  charge_unit text not null default 'per_use' constraint equipments_charge_unit_check check (charge_unit in ('per_use', 'per_item')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.drinks (
  id bigint generated by default as identity primary key,
  name text not null constraint drinks_name_check check (length(trim(name)) > 0),
  unit_price integer not null constraint drinks_unit_price_check check (unit_price >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.estimates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  meeting_room_id bigint not null references public.meeting_rooms(id),
  usage_hours integer not null constraint estimates_usage_hours_check check (usage_hours >= 1),
  number_of_people integer not null constraint estimates_number_of_people_check check (number_of_people >= 1),
  company_name_snapshot text not null constraint estimates_company_name_snapshot_check check (length(trim(company_name_snapshot)) > 0),
  facility_name_snapshot text not null constraint estimates_facility_name_snapshot_check check (length(trim(facility_name_snapshot)) > 0),
  meeting_room_name_snapshot text not null constraint estimates_meeting_room_name_snapshot_check check (length(trim(meeting_room_name_snapshot)) > 0),
  hourly_rate_snapshot integer not null constraint estimates_hourly_rate_snapshot_check check (hourly_rate_snapshot >= 0),
  room_fee integer not null constraint estimates_room_fee_check check (room_fee >= 0),
  equipment_fee integer not null default 0 constraint estimates_equipment_fee_check check (equipment_fee >= 0),
  drink_fee integer not null default 0 constraint estimates_drink_fee_check check (drink_fee >= 0),
  total_amount integer not null constraint estimates_total_amount_check check (total_amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estimates_room_fee_matches_rate check (room_fee = hourly_rate_snapshot * usage_hours),
  constraint estimates_total_matches_breakdown check (total_amount = room_fee + equipment_fee + drink_fee)
);

create table if not exists public.estimate_equipments (
  id bigint generated by default as identity primary key,
  estimate_id bigint not null references public.estimates(id) on delete cascade,
  equipment_id bigint not null references public.equipments(id),
  quantity integer not null constraint estimate_equipments_quantity_check check (quantity >= 1),
  equipment_name_snapshot text not null constraint estimate_equipments_equipment_name_snapshot_check check (length(trim(equipment_name_snapshot)) > 0),
  unit_price integer not null constraint estimate_equipments_unit_price_check check (unit_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estimate_equipments_estimate_equipment_key unique (estimate_id, equipment_id)
);

create table if not exists public.estimate_drinks (
  id bigint generated by default as identity primary key,
  estimate_id bigint not null references public.estimates(id) on delete cascade,
  drink_id bigint not null references public.drinks(id),
  quantity integer not null constraint estimate_drinks_quantity_check check (quantity >= 1),
  drink_name_snapshot text not null constraint estimate_drinks_drink_name_snapshot_check check (length(trim(drink_name_snapshot)) > 0),
  unit_price integer not null constraint estimate_drinks_unit_price_check check (unit_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estimate_drinks_estimate_drink_key unique (estimate_id, drink_id)
);

create index if not exists facilities_company_id_idx on public.facilities(company_id);
create index if not exists meeting_rooms_facility_id_idx on public.meeting_rooms(facility_id);
create index if not exists estimates_user_id_idx on public.estimates(user_id);
create index if not exists estimates_meeting_room_id_idx on public.estimates(meeting_room_id);
create index if not exists estimate_equipments_estimate_id_idx on public.estimate_equipments(estimate_id);
create index if not exists estimate_drinks_estimate_id_idx on public.estimate_drinks(estimate_id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles', 'companies', 'facilities', 'meeting_rooms', 'equipments',
    'drinks', 'estimates', 'estimate_equipments', 'estimate_drinks'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end;
$$;

